# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0e6d66447b30ad82a45cd5eb5f63a3d0f9141d57a23d45696e1bda826c0b79ce5f2c3be3f33fa48f9b056289def48abdfba0918e52e71e73d190633b6bccac2

test:
  secret_key_base: 1e0bf22a25b53c1232a0fc6aa62a35a38f6952afb44cf444113fb910adb869586aa6ed88049a0530e28bcbed44ab38d76be525976a160f38bd8e88aa09bd9e1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
